services:
  - type: web
    name: discovery-rag-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: WEAVIATE_URL
        value: $WEAVIATE_URL
      - key: WEAVIATE_API_KEY
        value: $WEAVIATE_API_KEY
      - key: OPENAI_API_KEY
        value: $OPENAI_API_KEY
    healthCheckPath: /
    autoDeploy: true
